services:
    app:
        restart: no
        build:
            context: deploy/docker
            dockerfile: local.dockerfile
        environment:
          PHP_IDE_CONFIG: 'serverName=${APP_URL}'
        volumes:
            - ./deploy/php/php-local.ini:/usr/local/etc/php/php.ini
            - ./deploy/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    redis:
        restart: no
        ports:
            - '127.0.0.1:${FORWARD_REDIS_PORT:-6379}:6379'
    nginx:
        restart: no
        ports:
            - "${APP_PORT:-80}:80"
    mariadb:
        restart: no
        ports:
            - "${FORWARD_DB_PORT:-3306}:3306"
