services:
  app:
    container_name: recom-stage-app
    build:
      context: deploy/docker
      dockerfile: local.dockerfile
    environment:
      PHP_IDE_CONFIG: 'serverName=${APP_URL}'
    volumes:
      - ./deploy/php/php-local.ini:/usr/local/etc/php/php.ini
      - ./deploy/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
  nginx:
    container_name: recom-stage-nginx
    ports:
      - "4500:80"
  redis:
    container_name: recom-stage-redis
    restart: no
    ports:
      - '127.0.0.1:${FORWARD_REDIS_PORT:-6390}:6379'
  mariadb:
    container_name: recom-stage-mariadb
    restart: no
    ports:
      - "${FORWARD_DB_PORT:-3309}:3306"
  worker:
    container_name: recom-stage-worker
